name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Only login to Docker Hub when pushing tags
      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version information
        id: extract_versions
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # Remove leading 'v' if present
          TAG=${TAG#v}

          # Extract Kamal and Infisical versions
          KAMAL_VERSION=$(echo $TAG | cut -d'-' -f1)
          INFISICAL_VERSION=$(echo $TAG | cut -d'-' -f2)

          echo "tag=${TAG}" >> $GITHUB_OUTPUT

          echo "Extracted versions - Kamal: ${KAMAL_VERSION}, Infisical: ${INFISICAL_VERSION}"

      - name: Determine Docker tags
        id: docker_tags
        run: |
          TAGS="ghcr.io/${{ github.repository_owner }}/snell-server:latest"

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            REF_NAME="${{ github.ref_name }}"
            # If tag starts with 'v', keep both original tag and tag without 'v'
            CLEAN_TAG="${REF_NAME#v}"

            TAGS="${TAGS},ghcr.io/${{ github.repository_owner }}/snell-server:${REF_NAME}"

            # Add Docker Hub tags
            TAGS="${TAGS},${{ secrets.DOCKERHUB_USERNAME }}/snell-server:${REF_NAME}"
            TAGS="${TAGS},${{ secrets.DOCKERHUB_USERNAME }}/snell-server:latest"
          fi

          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
